feat: add support for malaysia itn
gigapay/python-stdnum pull request #32
Opened 2024-06-06 04:36 UTC by gustav

2024-06-07 08:27 UTC, EmberCraze commented on stdnum/my/itn.py
> +        raise InvalidFormat()
There is no need for else in this case, the if does an early exit

2024-06-07 08:32 UTC, EmberCraze requested changes
Some small changes to the checks

2024-06-10 08:59 UTC, gustav commented on stdnum/my/itn.py
> +        if not (10 <= len(number) <= 13):
I realise we used an outdated document for the formats. Have updated with the new version.

2024-06-10 09:00 UTC, gustav commented on stdnum/my/__init__.py
> +from stdnum.sg import itn as business_tin  # noqa: F401
the itn is the business tin, will use nric for individuals

2024-06-11 14:57 UTC, merged